BACK-END PROJETO DE INTEGRAÇÃO 04.
pdrflp0/integration_project_backend pull request #5
Opened 2024-05-16 16:44 UTC by pdrflp0

- Swagger configuration inside the "configuration" folder.
   - Added folder and classes "controllers", "services" and "repositories".
   - App for starting tomcat/springboot server.
   - "application.properties" with all the necessary data (ports, addresses) for the successful connection.
   - Spring Framework, SpringBoot and SpringFox dependencies.

### Changed
   - "bd.sql" moved into the backend resources folder.
   - "hibernate.cfg.xml" re-formatted for better code compression.

### Removed
   - Hibernate configuration inside the "configuration" folder.
   - Back-end DAO classes.
   - Unnecessary dependencies in the project 04.

2024-05-17 15:46 UTC, Bacuriim requested changes
Foram encontrados alguns pontos de melhoria a serem feitos!

2024-05-17 15:46 UTC, Bacuriim commented on src/main/java/br/eletra/backend/controllers/CategoryController.java
> +    }
Mudar o value de "Return new category" para "New category".

2024-05-17 15:46 UTC, Bacuriim commented on src/main/java/br/eletra/backend/controllers/LineController.java
> +    }
Mudar o value "Return new Line" para "New line".

2024-05-17 15:46 UTC, Bacuriim commented on src/main/java/br/eletra/backend/controllers/ModelController.java
> +    }
Mudar o value "Return new model" para "New model".

2024-05-17 15:46 UTC, Bacuriim commented on src/main/java/br/eletra/backend/entity/ModelEntity.java
> +    @GeneratedValue(strategy=GenerationType.IDENTITY)
Separar esse "=" com um espaço antes e um depois.

2024-05-17 15:46 UTC, Bacuriim commented on src/main/java/br/eletra/backend/entity/ModelEntity.java
> +    public ModelEntity(String modelName , Short id) {
Remover o espaço antes da virgula.

2024-05-17 15:46 UTC, Bacuriim commented on src/main/java/br/eletra/backend/entity/ModelEntity.java
> +    public void ModelEntity(CategoryEntity category , String modelName){
Remover o espaço antes da virgula.

2024-05-17 15:46 UTC, Bacuriim commented on src/main/java/br/eletra/backend/entity/CategoryEntity.java
> +    public CategoryEntity(String name , Short id) {
Remover o espaço antes da virgula.

2024-05-17 15:46 UTC, Bacuriim commented on src/main/java/br/eletra/backend/entity/LineEntity.java
> +    public LineEntity(String name , Short id) {
Remover o espaço antes da virgula.

2024-05-17 18:23 UTC, XxTaro requested changes
Foi realizado o code review e foram encontrados pontos para melhoria

2024-05-17 18:23 UTC, gustavo-lopes-dev commented on src/main/java/br/eletra/backend/AppTest.java
Qual seria o motivo do nome da classe ser "AppTest"?

2024-05-17 18:23 UTC, XxTaro commented on src/main/java/br/eletra/backend/controllers/CategoryController.java
> +    }
Favor, não retornar uma String no método de update, e sim o proprio objeto salvo no banco, assim como é feito no método "postCategoryEntity"

2024-05-17 18:23 UTC, XxTaro commented on src/main/java/br/eletra/backend/controllers/CategoryController.java
> +    }
Favor, melhorar retorno desse método, no caso ou retornar um valor booleano para retornar se realmente foi possível deletar esse item (porém, o método "delete" do JPA não retorna nada, logo seria interessante uma verificação se aquele item ainda continua no banco) ou então ser um método void

2024-05-17 18:23 UTC, XxTaro commented on src/main/java/br/eletra/backend/controllers/LineController.java
> +    }
Favor, não retornar uma String no método de update, e sim o proprio objeto salvo no banco, assim como é feito no método "postLineEntity"

2024-05-17 18:23 UTC, XxTaro commented on src/main/java/br/eletra/backend/controllers/LineController.java
> +    }
Favor, melhorar retorno desse método, no caso ou retornar um valor booleano para retornar se realmente foi possível deletar esse item (porém, o método "delete" do JPA não retorna nada, logo seria interessante uma verificação se aquele item ainda continua no banco) ou então ser um método void

2024-05-17 18:23 UTC, XxTaro commented on src/main/java/br/eletra/backend/controllers/ModelController.java
> +    }
Favor, não retornar uma String no método de update, e sim o proprio objeto salvo no banco, assim como é feito no método "postModelEntity"

2024-05-17 18:23 UTC, XxTaro commented on src/main/java/br/eletra/backend/controllers/ModelController.java
> +    }
Favor, melhorar retorno desse método, no caso ou retornar um valor booleano para retornar se realmente foi possível deletar esse item (porém, o método "delete" do JPA não retorna nada, logo seria interessante uma verificação se aquele item ainda continua no banco) ou então ser um método void

2024-05-20 14:34 UTC, pdrflp0 commented on src/main/java/br/eletra/backend/controllers/CategoryController.java
> +    }
Feito!

2024-05-20 14:35 UTC, pdrflp0 commented on src/main/java/br/eletra/backend/controllers/LineController.java
> +    }
Feito!

2024-05-20 14:36 UTC, pdrflp0 commented on src/main/java/br/eletra/backend/controllers/ModelController.java
> +    }
Feito!

2024-05-20 14:36 UTC, pdrflp0 commented on src/main/java/br/eletra/backend/entity/ModelEntity.java
> +    @GeneratedValue(strategy=GenerationType.IDENTITY)
Feito!

2024-05-20 14:39 UTC, pdrflp0 commented on src/main/java/br/eletra/backend/entity/ModelEntity.java
> +    public ModelEntity(String modelName , Short id) {
Feito!

2024-05-20 14:40 UTC, pdrflp0 commented on src/main/java/br/eletra/backend/entity/ModelEntity.java
> +    public void ModelEntity(CategoryEntity category , String modelName){
Feito!

2024-05-20 14:40 UTC, pdrflp0 commented on src/main/java/br/eletra/backend/entity/CategoryEntity.java
> +    public CategoryEntity(String name , Short id) {
Feito!

2024-05-20 14:41 UTC, pdrflp0 commented on src/main/java/br/eletra/backend/entity/LineEntity.java
> +    public LineEntity(String name , Short id) {
Feito!

2024-05-20 14:44 UTC, pdrflp0 commented on src/main/java/br/eletra/backend/AppTest.java
Foi por conta de que no início do projeto eu criei com o intuito de testar se o springboot estava funcionando de fato no projeto, ao decorrer do projeto percebi que não seria de fato um "AppTest" já que eu teria que sempre inicializar primeiro do que a main do front e fiquei de alterar esse nome. Acabei alterando para "SpringApp", valeu lopes!

2024-05-20 14:47 UTC, pdrflp0 commented on src/main/java/br/eletra/backend/controllers/CategoryController.java
> +    }
Feito!

2024-05-20 15:25 UTC, pdrflp0 commented on src/main/java/br/eletra/backend/controllers/CategoryController.java
> +    }
Feito!

2024-05-21 13:58 UTC, pdrflp0 commented on src/main/java/br/eletra/backend/controllers/LineController.java
> +    }
Feito!

2024-05-21 14:02 UTC, pdrflp0 commented on src/main/java/br/eletra/backend/controllers/LineController.java
> +    }
Feito!

2024-05-21 14:05 UTC, pdrflp0 commented on src/main/java/br/eletra/backend/controllers/ModelController.java
> +    }
Feito!

2024-05-21 14:12 UTC, pdrflp0 commented on src/main/java/br/eletra/backend/controllers/ModelController.java
> +    }
Feito!

2024-05-23 17:54 UTC, XxTaro approved these changes
Não foram encontradas novas pendências

2024-05-24 04:07 UTC, merged