Feature/integration project backend 05
pdrflp0/integration_project_backend pull request #8
Opened 2024-06-21 16:11 UTC by pdrflp0

2024-06-22 15:40 UTC, XxTaro requested changes
Foi realizado o code review e foram indentificados pontos para melhoria e/ou correção

2024-06-22 15:40 UTC, XxTaro commented on src/test/java/br/eletra/backend/controllers/CategoryControllerTest.java
Não foi testado o caso de teste quando o categoryEntity for diferente de nulo nos testes do método deleteCategoryEntity()

2024-06-22 15:40 UTC, XxTaro commented on src/test/java/br/eletra/backend/controllers/LineControllerTest.java
Não foi testado o caso de teste quando o LineEntity for igual a nulo nos testes do método deleteLineEntity(). No mais, também, corrigir o nome da varíavel dentro do teste, o correto deveria ser lineEntity

2024-06-22 15:40 UTC, XxTaro commented on src/test/java/br/eletra/backend/controllers/ModelControllerTest.java
> +    private CategoryEntity category;
essa varíavel não é usada, favor, apagá-la

2024-06-22 15:40 UTC, XxTaro commented on src/test/java/br/eletra/backend/controllers/ModelControllerTest.java
Não foi testado o caso de teste quando o modelEntity for igual a nulo nos testes do método deleteModelEntity().

2024-06-24 19:29 UTC, pdrflp0 commented on src/test/java/br/eletra/backend/controllers/CategoryControllerTest.java
Corrigido ✅

2024-06-24 19:43 UTC, pdrflp0 commented on src/test/java/br/eletra/backend/controllers/LineControllerTest.java
Corrigido ✅

2024-06-24 19:51 UTC, pdrflp0 commented on src/test/java/br/eletra/backend/controllers/ModelControllerTest.java
Corrigido ✅

2024-06-25 16:45 UTC, pdrflp0 commented on src/test/java/br/eletra/backend/controllers/ModelControllerTest.java
> +    private CategoryEntity category;
Corrigido ✅

2024-06-30 15:26 UTC, XxTaro requested changes
Foram encontrados prontos para correção

2024-06-30 15:26 UTC, XxTaro commented on src/test/java/br/eletra/backend/controllers/CategoryControllerTest.java
> +                .thenReturn(null); // Segunda chamada, após exclusão, retorna null
Corrigir mock, está sendo realizado dois "thenReturn", deve ser chamada apenas uma

2024-06-30 15:26 UTC, XxTaro commented on src/test/java/br/eletra/backend/controllers/LineControllerTest.java
> +        when(repository.findByLineName("Line0")).thenReturn(lineEntity).thenReturn(null);
Corrigir mock, está sendo realizado dois "thenReturn", deve ser chamada apenas uma

2024-07-01 07:30 UTC, pdrflp0 commented on src/test/java/br/eletra/backend/controllers/LineControllerTest.java
> +        when(repository.findByLineName("Line0")).thenReturn(lineEntity).thenReturn(null);
Corrigido ✅

2024-07-01 07:41 UTC, pdrflp0 commented on src/test/java/br/eletra/backend/controllers/CategoryControllerTest.java
> +                .thenReturn(null); // Segunda chamada, após exclusão, retorna null
Corrigido ✅

2024-07-12 12:32 UTC, closed without merging